### ISSUE TITLE
剪枝的时候报错

### ISSUE THREAD

**Issue by arnozeng** [linklist2/yolov5-6.2-pruning#1]
![image](https://user-images.githubusercontent.com/64408767/196122183-ad06aebc-2d44-41cf-9879-ba52b4680605.png)
你好， 我按照说的步骤，在执行剪枝的时候，报了上面的错误。请问这是什么问题导致的吗？

**Comment by linklist2** [comment]
@arnozeng 看问题是出现在了剪枝后，进行模型验证的时候。
` valrun(
        data=data_dict,
        model=model,
        dataloader=dataloader,
        batch_size=opt.batch_size,
        imgsz=opt.imgsz,
        workers=opt.workers,
        half=opt.half,
        plots=False
    )`
这一部分是直接调用yolov5原有的val.py中的代码，如果是这里错误的话，请检查下你正在使用的代码是否是yolov5 6.2版本。

**Comment by arnozeng** [comment]
> @arnozeng 看问题是出现在了剪枝后，进行模型验证的时候。 ` valrun( data=data_dict, model=model, dataloader=dataloader, batch_size=opt.batch_size, imgsz=opt.imgsz, workers=opt.workers, half=opt.half, plots=False )` 这一部分是直接调用yolov5原有的val.py中的代码，如果是这里错误的话，请检查下你正在使用的代码是否是yolov5 6.2版本。

是最新版本的， 我是直接那MASTER版本训练

**Comment by linklist2** [comment]
@arnozeng 我自己在本地机器上又试了下，仍然是可以的

**Comment by linklist2** [comment]
@arnozeng 你要不再重新clone一下我的项目再按照步骤试试；或者用pycharm打开调试下，这个代码错误提示是stride对不上，要一个int或者只有一个元素的list，现在给了一个[1,1]

**Comment by arnozeng** [comment]
好的。 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linklist2/yolov5-6.2-pruning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月17日(星期一) 晚上6:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linklist2/yolov5-6.2-pruning] 剪枝的时候报错 (Issue #1)





 
@arnozeng 你要不再重新clone一下我的项目再按照步骤试试；或者用pycharm打开调试下，这个代码错误提示是stride对不上，要一个int或者只有一个元素的list，现在给了一个[1,1]
