### ISSUE TITLE
No module named 'yolo_pruned'

### ISSUE THREAD

**Issue by chunguangqu** [linklist2/yolov5-6.2-pruning#2]
你好，当我把第三步的剪枝后的模型无法进行检测，或者第四步微调训练后的模型也无法进行检测或者模型转换，均报如下的错误，请问是哪里的问题呢？
报错信息：No module named 'yolo_pruned'

**Comment by linklist2** [comment]
可以加我qq：2273098543详细探讨一下

**Comment by changliwu** [comment]
请问这个问题怎么解决？
