### ISSUE TITLE
can't train_sparity

### ISSUE THREAD

**Issue by zqyby** [linklist2/yolov5-6.2-pruning#3]
您好！
我使用你的代码可以进行正常训练，但是当进行稀疏化训练时就训练不了，报错信息显示找不到训练标签。让我疑惑的是如果找不到训练标签，那么应该正常训练也进行不了啊。恳请您百忙之中解答我一下这个疑惑

**Comment by linklist2** [comment]
不好意思，请添加我qq2273098543，我最近暂时很忙，有空的时候我再看看



---Original---
From: ***@***.***&gt;
Date: Fri, May 12, 2023 09:46 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [linklist2/yolov5-6.2-pruning] can't train_sparity (Issue #3)




 
您好！
 我使用你的代码可以进行正常训练，但是当进行稀疏化训练时就训练不了，报错信息显示找不到训练标签。让我疑惑的是如果找不到训练标签，那么应该正常训练也进行不了啊。恳请您百忙之中解答我一下这个疑惑
